#!/bin/bash

if [ -x /opt/local/bin/port ]; then
	which bats > /dev/null || rpk action sudo port install bats-core
elif [ -x /usr/bin/apt-get ]; then
	which bats > /dev/null || rpk action sudo apt-get --yes install bats
elif [ -x /usr/local/bin/brew ] || [ -x /opt/homebrew/bin/brew ]; then
	which bats > /dev/null || rpk action brew install bats-core
elif [ -x /usr/bin/dnf ]; then
	which bats > /dev/null || rpk action sudo dnf install -y bats
elif [ -x /usr/bin/pacman ]; then
	which bats > /dev/null || rpk action sudo pacman -S --noconfirm bats
fi
