#!/bin/bash

function die() {
	echo "$@"
	exit 100
}

PACKAGE=$(bin/rpk identity)
VERSION=$1

test -z "$VERSION" && VERSION=$(bin/rpk versions | tail -1)

COMMIT=$(bin/rpk commit "$VERSION")
test -z "$COMMIT" && die "version $VERSION has no commit hash"

TARGET=$(bin/rpk bundle "$(bin/rpk type)")/$PACKAGE-$VERSION

BRANCH=$(git branch --show-current)
trap "git checkout $BRANCH --force" EXIT

git config advice.detachedHead false
git checkout "$COMMIT" || die "failed to checkout $COMMIT for version $VERSION"

./configure --prefix="$TARGET"
make
make install

git checkout "$BRANCH" --force
