#!/bin/bash

function die() {
	echo "$@"
	exit 100
}

PACKAGE=$(rpk identity)
VERSION=$1

test -z "$VERSION" && VERSION=$(rpk versions | tail -1)

COMMIT=$(rpk commit "$VERSION")
test -z "$COMMIT" && die "version $VERSION has no commit hash"

TARGET=$(rpk bundle "$(rpk type)")/$PACKAGE-$VERSION

BRANCH=$(git branch --show-current)
trap 'git checkout "$BRANCH" --force' EXIT

git config advice.detachedHead false
git checkout "$COMMIT" || die "failed to checkout $COMMIT for version $VERSION"

./configure --prefix="$TARGET"
make
make install

git checkout "$BRANCH" --force
